### ISSUE TITLE
Need to edit script for use over WiFi

### ISSUE THREAD

**Issue by axelclark** [fhunleth/nerves_firmware_ssh#10]
I'm using a MacBook and updating my rpi3 over WiFi using [Nerves_Network](https://github.com/nerves-project/nerves_network).  I have it working, but I had to work through some errors:

When I try to use `MIX_TARGET=rpi3 mix firmware.push 192.168.0.199`, I get:
```elixir
** (Mix) couldn't connected to 192.168.0.199: check private key and the passphrase protecting it
```
This error initially led me to believe the `/n` newline you get from using
```elixir
File.read!(Path.join(System.user_home!, ".ssh/id_rsa.pub"))
```
was causing an error, but I don't believe that was the issue (at least it isn't an issue when you use the script).

Instead of the mix task, I tried using the script as it is generated.  However, it exited without the upload:
```bash
> mix nerves.gen.script.upload
> bash firmware_push 192.168.0.199
Uploading ./_build/rpi3/dev/nerves/images/my_ssh_firmware.fw to 192.168.0.199...
>
```

However, if I comment out the last `if` block of the script:
```bash
# if [ "$(uname -s)" = "Darwin" ]; then
#     DESTINATION_IP=$(arp -n $DESTINATION | sed 's/.* (\([0-9.]*\).*/\1/' || exit 0)
#     if [ -z "$DESTINATION_IP" ]; then
#         echo "Can't resolve $DESTINATION"
#         exit 1
#     fi

#     IS_DEST_LL=$(echo $DESTINATION_IP | grep '^169\.254\.')
#     if [ -n "$IS_DEST_LL" ]; then
#         LINK_LOCAL_IP=$(ifconfig | grep 169.254 | sed 's/.*inet \([0-9.]*\) .*/\1/')
#         if [ -z "$LINK_LOCAL_IP" ]; then
#             echo "Can't find an interface with a link local address?"
#             exit 1
#         fi

#         # If a link local address, then force ssh to bind to the link local IP
#         # when connecting. This fixes an issue where the ssh connection is bound
#         # to another Ethernet interface. The TCP SYN packet that goes out has no
#         # chance of working when this happens.
#         SSH_OPTIONS="$SSH_OPTIONS -b $LINK_LOCAL_IP"
#     fi
# fi
```
the script works:
```bash
> bash firmware_push 192.168.0.199
Uploading ./_build/rpi3/dev/nerves/images/my_ssh_firmware.fw to 192.168.0.199...
Running fwup...
fwup: Upgrading the B partition
100%
Elapsed time: 22.300s
Rebooting...
>
```

I have it working which I'm super excited about, but I figured I would submit this as an issue in case anyone else runs into similar errors.

**Comment by fhunleth** [comment]
Something else is failing. Unfortunately, the `set -e` is hiding it. My guess is that you don't have `arp` or `sed` or `grep`. Could you see which one is missing?

**Comment by axelclark** [comment]
I checked and `arp`, `sed`, and `grep` appear to be installed.  I was/am getting another error:
```bash
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```
but it hasn't impacted it working either way.

I added `|| exit 0` to the line below and it is working now.  Could that have been the issue?
```bash
    IS_DEST_LL=$(echo $DESTINATION_IP | grep '^169\.254\.' || exit 0)

**Comment by fhunleth** [comment]
Yes. The `IS_DEST_LL` line should have a `|| exit 0`. Could you send a PR with this?

As for the `stat` error, `stderr` should be redirected to `/dev/null` so that no one sees it. I'm not sure why I didn't see the error message when I tested this, but any error is fine. This is for the GNU stat vs. BSD stat detection code and erroring out does the right thing on OSX.
